# Generated by Django 4.2.24 on 2025-12-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference_code',
            field=models.CharField(default='TEMPREF12345', editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
