# Generated by Django 4.2.24 on 2025-12-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0002_booking_reference_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reference_code',
            field=models.CharField(default='TEMPMSG00000', editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
