# Generated by Django 4.2.24 on 2025-12-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0004_alter_contactmessage_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='reference_code',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
