# Generated by Django 4.2.24 on 2025-12-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0005_alter_contactmessage_reference_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='reference_code',
        ),
    ]
