# Generated by Django 4.2.24 on 2025-12-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0006_remove_contactmessage_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
